name: Build Infographics

on:
  push:
    branches: [ main ]
    paths:
      - '**.csv'
      - '**.xlsx'
      - 'notebooks/**.ipynb'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib jupyter nbconvert

      - name: Execute notebook & export PNG
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute notebooks/fintech_funding_overview.ipynb \
            --output executed.ipynb

          jupyter nbconvert \
            executed.ipynb --to html

      # optional: commit the generated files back to the repo
      - name: Commit infographic
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.html'  # adjust if you later output PNGs/SVGs
          message: 'Auto-update infographic'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

