name: Build Infographics

on:
  push:
    branches: [ main ]
    paths:
      - '**.csv'
      - '**.xlsx'
      - 'notebooks/**.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib jupyter nbconvert

      - name: Prepare infographics folder
        run: mkdir -p infographics

      # Fintech funding overview infographic
      - name: Run & export fintech funding overview
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute notebooks/fintech_funding_overview.ipynb \
            --output notebooks/fintech_funding_overview.executed.ipynb

          jupyter nbconvert \
            notebooks/fintech_funding_overview.executed.ipynb \
            --to html \
            --output infographics/fintech_funding_overview.html

      # Treasury cash balances heatmap infographic
      - name: Run & export treasury cash balances heatmap
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute notebooks/treasury_cash_balances_heatmap.ipynb \
            --output notebooks/treasury_cash_balances_heatmap.executed.ipynb

          jupyter nbconvert \
            notebooks/treasury_cash_balances_heatmap.executed.ipynb \
            --to html \
            --output infographics/treasury_cash_balances_heatmap.html

      - name: Commit updated infographics
        uses: EndBug/add-and-commit@v9
        with:
          add: 'infographics/*.html'
          message: 'Auto-update infographics'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

