name: Build Infographics

on:
  push:
    branches: [ main ]
    paths:
      - '**.csv'
      - '**.xlsx'
      - 'notebooks/**.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib jupyter nbconvert

      - name: Generate Fintech PNG
        run: |
          jupyter nbconvert \
            --to png \
            --execute notebooks/fintech_funding_overview.ipynb \
            --output fintech_funding_overview.png \
            --output-dir infographics

      - name: Generate Treasury PNG
        run: |
          jupyter nbconvert \
            --to png \
            --execute notebooks/treasury_cash_balances_heatmap.ipynb \
            --output treasury_cash_balances_heatmap.png \
            --output-dir infographics

      - name: Commit infographic PNGs
        uses: EndBug/add-and-commit@v9
        with:
          add: 'infographics/*.png'
          message: 'Auto-update infographic PNGs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
