name: Build Infographics

on:
  push:
    branches: [ main ]
    paths:
      - '**.csv'
      - '**.xlsx'
      - 'notebooks/**.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib jupyter nbconvert

      - name: Create output directories
        run: |
          mkdir -p infographics
          mkdir -p notebooks

      - name: Execute notebook & export HTML
        run: |
          # 1) Execute the notebook, writing executed.ipynb into notebooks/
          jupyter nbconvert \
            --to notebook \
            --execute notebooks/fintech_funding_overview.ipynb \
            --output executed.ipynb \
            --output-dir notebooks

          # 2) Convert that executed.ipynb to HTML in infographics/
          jupyter nbconvert \
            --to html \
            --output fintech_funding_overview.html \
            --output-dir infographics \
            notebooks/executed.ipynb

      - name: Commit infographic
        uses: EndBug/add-and-commit@v9
        with:
          add: 'infographics/*.html'
          message: 'Auto-update infographic'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

