name: Build Infographics

on:
  push:
    branches: [ main ]
    paths:
      - '**.csv'
      - '**.xlsx'
      - 'notebooks/**.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib jupyter nbconvert

      - name: Create output directory
        run: mkdir -p infographics

      - name: Execute notebook & export HTML
        run: |
          # Execute and overwrite a copy under notebooks/
          jupyter nbconvert \
            --to notebook \
            --execute notebooks/fintech_funding_overview.ipynb \
            --output notebooks/executed.ipynb

          # Convert that executed notebook to HTML in infographics/
          jupyter nbconvert \
            notebooks/executed.ipynb --to html \
            --output infographics/fintech_funding_overview.html

      - name: Commit infographic
        uses: EndBug/add-and-commit@v9
        with:
          add: 'infographics/*.html'
          message: 'Auto-update infographic'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

